version: '2'

networks:
  weikebala:

services:
  short_link:
    build: short_link
    networks:
      - weikebala
    depends_on:
      - redis
    expose:
      - "9001"

  nginx:
    build: nginx
    networks:
      - weikebala
    depends_on:
      - short_link
    ports:
      - "80:80"

  redis:
    image: "redis"
    networks:
    - weikebala
    expose:
    - "6379"



