version: '2'

services:
  short_link:
    build: short_link
    networks:
      - weikebala
    depends_on:
      - redis
    expose:
      - "9001"
    labels:
      - "traefik.backend=short_link"
      - "traefik.frontend.rule=Host:apigw.fileserver.com"
      - "traefik.docker.port=9001"

  redis:
    image: "redis"
    networks:
    - weikebala
    expose:
    - "6379"
networks:
  apinetwork:
    external:
      name: fileserver



